apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: LoadBalancer
  ports:
  - name: jenkins-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: jenkins
