apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: bitroid/jenkinsnginx:v4
        ports:
        - containerPort: 8080
          name: jenkins-port
        - containerPort: 80
          name: nginx
