# This is a basic workflow to help you get started with Actions

name: kubernetes_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      # Runs a set of commands using the runners shell
      - name: Clean up before deployment
        run: |
          kubectl delete -f jenkins.configmap.yaml
          kubectl delete -f jenkins-patch.yaml
          kubectl delete -f jenkins-service.yaml
          

      - name: deploying jenkins config map
        run: kubectl apply -f jenkins.configmap.yaml

      - name: deploying jenkins
        run: kubectl apply -f jenkins-patch.yaml
        
      - name: wait for jenkins to up 
        run: sleep 280
        
      - name: jenkins to verify nginx
        run: kubectl exec -it deployment.apps/jenkins -- nginx -t
        
      - name: deploying jenkins network service
        run: kubectl apply -f jenkins-service.yaml
        
      - name: verify deployments
        run: kubectl get all

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
